In [8]:
import json
import pandas as pd
import codecs
from pprint import pprint

#Exploring the data from TELE2

data = []

#The following features were interesting to our project
columnlist = ['timestamp', 'lat', 'lon','locationAccuracy','accountName','domainId', 'id']

with open('vasttrafik.json') as file:
    for line in file:
        #Pre-processing the data
        parts = line.split(' ',1)
        parts[1] = json.loads(parts[1])
        #There were 2 kinds of data, one called (2control/synthesized_events) and one called (2control/protocol)
        #We were only interested in the control data so we filter based on our desired columns
        try:
            timestamp = parts[1]['timestamp']
            lat = parts[1]['payload']['derived']['location']['lat']
            lon = parts[1]['payload']['derived']['location']['lon']
            locationAccuracy = parts[1]['payload']['derived']['locationAccuracy']
            accountName = parts[1]['payload']['derived']['subscriber']['accountName']
            domainID = parts[1]['payload']['derived']['subscriber']['domainId']
            ID = parts[1]['payload']['derived']['subscriber']['id']
            data.append([timestamp, lat, lon, locationAccuracy, accountName, domainID, ID])
        except:
            pass
df = pd.DataFrame(data, columns = columnlist)
df.head()

,timestamp,lat,lon,locationAccuracy,accountName,domainId,id
0,2019-05-09T18:59:20.242Z,57.703447,11.960967,1381,Västtrafik,jpo109998405,89462036051001307021
1,2019-05-09T18:59:20.244Z,57.703447,11.960967,1381,Västtrafik,jpo109998405,89462036051001307021
2,2019-05-09T18:59:00.850Z,57.649579,14.687408,1838,Västtrafik,jpo109998405,89462036051001308771
3,2019-05-09T18:59:01.177Z,58.030253,11.543153,2610,Västtrafik,jpo109998405,89462046051009174561
4,2019-05-09T18:59:02.186Z,58.376907,12.31864,1827,Västtrafik,jpo109998405,89462046051009015921